### ISSUE TITLE
Dialog font missing

### ISSUE THREAD

**Issue by svanpoeck** [jgraph/drawio#1040]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When opening the "Open file..." dialog for any reason, the used font is not available and empty squares are displayed instead of where text should be. This happens when clicking on "Open existing diagram" as well as when "Save as..." or "Export as..." a diagram.

**To Reproduce**
1. Open draw.io (the Ubuntu snap)
2. Close draw.io
3. Open draw.io again
4. Click "Open existing diagram"
5. Click on notification "" is ready
6. The File manager dialog uses a non-present font

**Expected behavior**
The File manager dialog should display normally using an existing font

**Screenshots**
![draw-io-issue](https://user-images.githubusercontent.com/287523/87527029-d5ec2c00-c68b-11ea-87c0-6d092f59b62f.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 13.3.9 (snap revision 39)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 20.04
 - N/A, using Draw.io snap (which seems to be using Chromium browser)

**Smartphone (please complete the following information):**
 - N/A, using Ubuntu snap

**Additional context**
It seems you suffer from this bug in Chromium: https://bugs.launchpad.net/bugs/1864365

**Comment by svanpoeck** [comment]
Ah by the way, for those experiencing this issue, it can be solved -for the duration of a usage session- by deleting the snap's font cache : `rm -rf ~./snap/drawio/common/.cache/fontconfig/`

**Comment by secdoc** [comment]
This is still an issue at least with the snap package....

**Comment by frostybeard** [comment]
I also see this issue in Ubuntu 20.04. It makes Draw.io more or less unusable here. It was installed from Snapcraft. Issue seen in both stable 19.3.(?) and in 12.6.
![drawio_file_dialog](https://user-images.githubusercontent.com/1737038/181447630-41261bd4-db63-46f4-a4c8-7dd93ad54abb.png)
5

**Comment by frostybeard** [comment]
One more comment: When installed from a .deb from https://github.com/jgraph/drawio-desktop/releases/tag/v19.0.3 it works correctly.

**Comment by mtonkin2** [comment]
Hi all! Just wanted to ask if anything is being done & if this is still a problem for others? 20.7.4 from snap on Fedora 37.
My config (with gtk message, as could be relavant?):


$ drawio --version
Gtk-Message: 16:40:34.274: Failed to load module "pk-gtk-module"
Gtk-Message: 16:40:34.276: Failed to load module "pk-gtk-module"
20.7.4
16:40:34 mike@jaja-dingdong ~/.config/onedrive
$ uname -a
Linux jaja-dingdong 6.0.17-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 4 15:58:35 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
16:43:07 mike@jaja-dingdong ~/.config/onedrive

The

**Comment by PavoDive** [comment]
I had the problem with drawio just yersteday. Installed it via snap, and had to remove it, as it was mostly unusable because of this.

![image](https://user-images.githubusercontent.com/9052269/223212099-67ecf2b5-1136-46ce-ab05-8c0686583091.png)

I can confirm that with the AppImage downloaded today from [here](https://github.com/jgraph/drawio-desktop/releases) the problem **does not arise**.

**Comment by alambike** [comment]
Same issue here, after upgrade to Ubuntu 23.04, from Ubuntu 22.10.

In Ubuntu 22.10 it was working correctly, but after upgrade to 23.04,  Draw.io dialog windows is not usable. It seems that some required font is missing from my system... maybe in the upgrade to 23.04, some font could be uninstalled ?

**Comment by BzSpi** [comment]
I've fixed it with @alambike command, but as sudo user.
`sudo fc-cache -r -v`

**Comment by 00shorty** [comment]
worked for me on Ubuntu 23.04 as well :) thanks @BzSpi

**Comment by mehdiMj-ir** [comment]
I think this issue still exist on `Kubuntu 23.10` via `Snap` and it doesn't fix after fontconfig cache regeneration!
![Uploading Screenshot_20240317_135500.png…](Missing dialog fonts)

without sudo command:
```log
fc-cache -fv

Font directories:
        /home/mehdi/.local/share/fonts
        /usr/share/fonts
        /var/lib/snapd/desktop/fonts
        /usr/local/share/fonts
        /home/mehdi/.fonts
        /usr/share/fonts/croscore
        /usr/share/fonts/crosextra
        /usr/share/fonts/dejavu
        /usr/share/fonts/ko-nanum
        /usr/share/fonts/lohit-cros
***
/usr/share/fonts/truetype/wine: skipping, looped directory detected
/usr/share/fonts/type1/urw-base35: skipping, looped directory detected
/usr/share/fonts/X11/encodings/large: skipping, looped directory detected
/var/cache/fontconfig: not cleaning unwritable cache directory
/home/mehdi/.cache/fontconfig: cleaning cache directory
/home/mehdi/.cache/fontconfig: invalid cache file: da43223dd54fb3bb4243ae19d4b583b2-le64.cache-8
/home/mehdi/.cache/fontconfig: invalid cache file: 246184dc75a16901ca37d96895904249-le64.cache-8
/home/mehdi/.cache/fontconfig: invalid cache file: 4b14b093aebc79c320de5e86ae1d3314-le64.cache-8
/home/mehdi/.cache/fontconfig: invalid cache file: 807752c9e168308eb5108dacded5237a-le64.cache-8
/home/mehdi/.cache/fontconfig: invalid cache file: 53d14c92082a93e67d5078324eb314ca-le64.cache-8
/home/mehdi/.cache/fontconfig: invalid cache file: 158c65c810c0d352a587f5be66058e87-le64.cache-8
/home/mehdi/.cache/fontconfig: invalid cache file: e49e89034d371f0f9de17aab02136486-le64.cache-8
/home/mehdi/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded
```
With sudo command
```log
sudo fc-cache -r -v

Font directories:
        /root/.local/share/fonts
        /usr/share/fonts
        /root/.fonts
        /usr/local/share/fonts
        /usr/share/fonts/croscore
        /usr/share/fonts/crosextra
***
/usr/share/fonts/type1/urw-base35: skipping, looped directory detected
/usr/share/fonts/X11/encodings/large: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded
```

**Comment by nilskuhn** [comment]
Problem still existing with Kubuntu 24.04.

Downloaded deb didn't work for me either:
```
$ drawio                                             
[1710332:0121/155905.219135:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/drawio/chrome-sandbox is owned by root and has mode 4755.
[1]    1710332 trace trap (core dumped)  drawio
```

**Comment by Deeltjes** [comment]
None of the installer packages are working on Ubuntu 24.04 on publishing date of this comment. Default installation. Also tried version 26.0.15 which failed the same way.

1. Tried snap: drawio 26.0.16, fonts are missing. See screenshot earlier posts.
2. Tried drawio-amd64-26.0.16.deb: 
`bash
$ drawio 
[56587:0305/153814.647110:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/drawio/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
`
Mode 4755 is problematic for security.
Tried with libfuse2t64. (sudo apt install libfuse2t64). Still not working.
3. Tried :  drawio-x86_64-26.0.16.AppImage
`bash
$./drawio-x86_64-26.0.16.AppImage 
dlopen(): error loading libfuse.so.2
AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
`
Dependency for FUSE lib version 2. Which is outdated! 

Any ideas?
