### ISSUE TITLE
Pdf exports - only blank page appears

### ISSUE THREAD

**Issue by rmilosic** [jgraph/drawio#1075]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When exporting .pdf, any page exports totally blank.

**To Reproduce**
1. Go to 'File'
2. Click on 'Export as'
3. Select 'Pdf'
4. Select 'Current page' unselect other options
5. Click 'Export'.
6. Select 'Download'.
7. Open downloaded file with any pdf reader

**Expected behavior**
Pdf opens with exported flowchart.

**Screenshots**
[Video](https://drive.google.com/file/d/1Vd0mH455t0RatlBy8-7lUH-Wh-LQJyto/view?usp=sharing)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 13.5.7

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: 83

**Comment by rlemonn** [comment]
I'm experiencing the same issue as describe here and in the video.  Also using the latest version of draw-io.  Only blank pages appears.

**Comment by davidjgraph** [comment]
I wasn't able to repeat. What do you get for `ping exp.draw.io` ?

**Comment by rlemonn** [comment]
Problem continues.
As for what I get for ping exp.draw.io is this:

`PING exp.draw.io (104.22.57.156): 56 data bytes
64 bytes from 104.22.57.156: icmp_seq=0 ttl=61 time=14.486 ms
64 bytes from 104.22.57.156: icmp_seq=1 ttl=61 time=34.029 ms
64 bytes from 104.22.57.156: icmp_seq=2 ttl=61 time=14.399 ms
64 bytes from 104.22.57.156: icmp_seq=3 ttl=61 time=14.282 ms
64 bytes from 104.22.57.156: icmp_seq=4 ttl=61 time=16.271 ms
64 bytes from 104.22.57.156: icmp_seq=5 ttl=61 time=18.631 ms
64 bytes from 104.22.57.156: icmp_seq=6 ttl=61 time=19.034 ms
64 bytes from 104.22.57.156: icmp_seq=7 ttl=61 time=13.811 ms
64 bytes from 104.22.57.156: icmp_seq=8 ttl=61 time=39.656 ms
64 bytes from 104.22.57.156: icmp_seq=9 ttl=61 time=14.409 ms
64 bytes from 104.22.57.156: icmp_seq=10 ttl=61 time=14.166 ms
64 bytes from 104.22.57.156: icmp_seq=11 ttl=61 time=17.229 ms
64 bytes from 104.22.57.156: icmp_seq=12 ttl=61 time=15.638 ms
64 bytes from 104.22.57.156: icmp_seq=13 ttl=61 time=16.212 ms`

**Comment by rlemonn** [comment]
The ping command work it's just that I'm trying to put a multipages (5 pages) drawings into PDF and I have only blank pages in the PDF.

**Comment by mbaguley** [comment]
Same issue for me on Windows - with Chrome, Edge and Desktop app. Version diagrams.net 13.5.7. Chrome and Desktop produce a blank 2k file, Edge produces a larger file but also with no diagram, although it does produce the grid if selected.

**Comment by davidjgraph** [comment]
Please attach your diagram that recreates this

**Comment by mbaguley** [comment]
Example attached
[Example.zip](https://github.com/jgraph/drawio/files/5034890/Example.zip)

**Comment by davidjgraph** [comment]
Thanks, that recreates the issue for me

**Comment by rlemonn** [comment]
Here's mine @davidjgraph
[Organigramme SQET-5044 (futur SANS NOM).drawio.zip](https://github.com/jgraph/drawio/files/5036910/Organigramme.SQET-5044.futur.SANS.NOM.drawio.zip)

**Comment by rmilosic** [comment]
Hi @davidjgraph , this ceases to be an issue for me. Pdf export is working for me now.

**Comment by davidjgraph** [comment]
We pushed a fix in 13.6.2. Thanks for the report and reproduction case.

**Comment by rlemonn** [comment]
Hey guys, still having issue with my diagram and new version 13.6.2.
Only blank pages occurs
