### ISSUE TITLE
Export to pdf fails on browser, live version at draw.io

### ISSUE THREAD

**Issue by michaelsaxon** [jgraph/drawio#2023]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The live hosted version of drawio on draw.io returns an error 500 "Internal server error" when I try to export my diagram (or a test diagram containing only a single rectangle) as a pdf.

**To Reproduce**
1. Go to the hosted version on draw.io
2. Open a drawing
3. Click file->export as->pdf->any combination of options->download
4. The following error appears
**500 - Internal server error.**
There is a problem with the resource you are looking for, and it cannot be displayed.

**Expected behavior**
Successful export of my drawing as a pdf. (Png, other export options still work fine)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [14.6.13]

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Firefox]
 - Version [88.0.1]

**Additional context**
This is probably a backend problem with the server, not a problem with the repo itself, but couldn't find a more appropriate place to submit, apologies if this is wrong place to put this.

**Comment by davidjgraph** [comment]
Fixed. Thanks for report.

**Comment by zhenwang9102** [comment]
It seems that I encountered the same issue and the server error isn't still there. Could you double-check it? Thanks!

**Comment by michaelsaxon** [comment]
> It seems that I encountered the same issue and the server error isn't still there. Could you double-check it? Thanks!

I was also still having the issue as of 6 hours ago, but I just checked again and it seems to work now. Maybe retry your export now?

**Comment by TTTsuperpyer** [comment]
I was also still having the issue as of 6 hours ago, but I just checked again and it seems to work now. Maybe retry your export now?
