### ISSUE TITLE
Constraint connection points wrong with 90° rotation

### ISSUE THREAD

**Issue by axydraw** [jgraph/drawio#3469]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md)
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When rotating shapes with Ctrl+R or with Arrange-Rotate-90° then all connection points edited with `<constraint>` are wrong.

**Workaround**
Only when rotating manually with the shape symbol ⭮ or when entering angle degrees with numbers, the connection points are as expected.

**To Reproduce**
1. Edit a shape with non 1:1 aspect ratio.
2. Define a couple of connection points with `<connections><constraint x="..." y="..." /> <...> </connections>`.
3. Rotate the shape with Ctrl+R or with Arrange-Rotate-90°.
4. The connection points are missing and wrong (somehow condensed depending on aspect ratio).

**Expected behavior**
Shortcut Ctrl+R or Arrange-Rotate-90° shall behave like manual rotation or manual angle degree input.

**Screenshots**
See attached PNG file.

**Version:**
typo 13.9.6 (correct: 14.9.6) desktop offline version with Win 10 Pro 64 bit.
 
![drawio_rotation-error_v20210827](https://user-images.githubusercontent.com/88381003/131101092-e6a3b3df-16bc-489c-b344-d9031d9a392d.png)

**Comment by SimonFili** [comment]
I can confirm it's still there with version 21.6.8 in September 2023. Saw it with valve shape, added connections points, did a 90° rotation, the points are in the wrong place.  If I replace them while the shape is rotated, the points do not save in the right position.  Seems the points are only working with the original rotation of the shape.

**Comment by alechenken** [comment]
Still confirming this bug exists today. Connection points added after rotation do not end up where they are placed in the editor.

**Comment by Shredsauce** [comment]
Confirming again that this bug still exists in v26.0.9

To reproduce:
* Add any object into the scene
* Hover over and click the top-right rotate button to rotate the object by 90 degrees
* Right-click the object --> Edit Connection Points...
* Add multiple connections points to the Left
* Note that the connection points appear on the left of the object in the preview window
* Click Apply
* Hover over the object
* The connection points now appear at the top of the rotated object

**Comment by alderg** [comment]
Should be fixed.

**Comment by ll3141** [comment]
still present in 29.6.1

is there a reason why I'm not able to upload my example file?

**Comment by davidjgraph** [comment]
Please create a new issue with full environment and reproduction steps.
