### ISSUE TITLE
Editor vertically offset in confluence cloud

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#3665]
We have multiple reports of the draw.io editor having a blank area at the bottom of the display on confluence cloud.

Atlassian updated their AUI (Atlassian User Interface) for some users overnight and broke the layouting for us.

We understand that this will have an impact on your business operations. Unfortunately, the problem is in the parent iframe above us, over which we have no control.

The Atlassian incident is currently marked as high, https://jira.atlassian.com/browse/CONFCLOUD-75996. If this incident is affecting your business, you are welcome to state the impact in that ticket. The severity is currently marked as minor, meaning it is having a minimal impact on business operations.

**Comment by davidjgraph** [comment]
It looks like Atlassian updated their AUI (Atlassian User Interface) for some users overnight and broke the layouting for us. We are asking why such a change went out without any advance notice to us to test it.

**Comment by davidjgraph** [comment]
https://jira.atlassian.com/browse/CONFCLOUD-75937

The white section is a 314 pixel block affecting all apps. A large number of vendors are asking for immediate rollback.

**Comment by q-farshidalavimoghadam** [comment]
This is impacting me day-in day-out, I am sure there are so many others like me who have been impacted by this issue severely. How can it be a minor issue when it is pretty much making draw.io unusable?

**Comment by jaywon-song** [comment]
Currently, the team pays for Atlassian and draw.io, and draw.io is used a lot when designing development. Due to the currently reported issues, we are experiencing a lot of inconvenience while working on flowcharts and UML. For customers who purchase and use it directly, the issue is causing a lot of disruption to their business. I hope that the issue will be resolved as soon as possible. May I know how long it will take for the issue to be resolved?

**Comment by nickerber7** [comment]
Issue seems to be resolved. Using Chrome 112.0.5615.138 we do not see the vertical offset anymore.

**Comment by jaywon-song** [comment]
I'm currently working on it, but I've confirmed that the vertical offset doesn't appear and the screen comes out normally.

The Chrome I use is 114.0.5735.106.

Thank you for your mail.

**Comment by davidjgraph** [comment]
Atlassian have stated the issue is fixed in https://jira.atlassian.com/browse/CONFCLOUD-75996 and the blank space has gone.

Apologies to those affected. We're talking to Atlassian to encourage them to add 3rd party apps, like ours, to their testing when they make future changes in this area.

**Comment by jaywon-song** [comment]
@davidjgraph 

thank you for the quick response. 

Thanks to that, I didn't have much of a problem with my work.


> Atlassian have stated the issue is fixed in https://jira.atlassian.com/browse/CONFCLOUD-75996 and the blank space has gone.
> 
> Apologies to those affected. We're talking to Atlassian to encourage them to add 3rd party apps, like ours, to their testing when they make future changes in this area.

**Comment by GopinathRajasekaran** [comment]
I still see the vertical offset issue, and use Chrome Version 114.0.5735.110.

**Comment by GopinathRajasekaran** [comment]
Tried now, and I don't see such an issue... it's working fine... not sure what caused the previous instance...

**Comment by q-farshidalavimoghadam** [comment]
I am still experiencing this issue. On Chrome Version 114.0.5735.110 (Official Build) (64-bit)

**Comment by davidjgraph** [comment]
Anyone still seeing the issue try clearing browser cache.

If that doesn't work file a ticket at https://drawio.atlassian.net/servicedesk/customer/portal/14 including your SEN for draw.io.

**Comment by davidjgraph** [comment]
https://community.developer.atlassian.com/t/aui-is-being-upgraded-to-v8-8-4/70321/5

Atlassian have stated that CSS changes to the interface will go into the canary build, which is the pre-production build of Confluence we get access to. This should avoid a repeat.
