### ISSUE TITLE
[Feature Request] Latin-Modern font on the math typesetting

### ISSUE THREAD

**Issue by mhgharieb** [jgraph/drawio#451]
I know that draw.io uses Mathjax to render latex math. Therefore,  draw.io follows the default configuration of Mathjax which uses "MathJax TeX" font by default. Mathjax also supports "Latin-Modern" font which is the actual font used in Latex.
Actually, I am able to reconfigure a local version of draw.io to use "Latin-Modern" in the GUI but the export files "SVG" or "PDF" still use "MathJax TeX" (STIXGeneral-Italic) font by default.

It will be better to use "Latin-Modern" font, so it is consistent with the latex

**Comment by alderg** [comment]
What configuration are you using to change the font?

**Comment by wookayin** [comment]
+1. Please add the following in the `MathJax.Hub.Config`:
```
"HTML-CSS": { availableFonts: ["TeX"] }
```

**Comment by alderg** [comment]
We tested it and there are clipping issues for matrices (see https://www.draw.io/#Uhttps%3A%2F%2Fjgraph.github.io%2Fdrawio-diagrams%2Fdiagrams%2Fmath.xml)

**Comment by mhgharieb** [comment]
> We tested it and there are clipping issues for matrices (see https://www.draw.io/#Uhttps%3A%2F%2Fjgraph.github.io%2Fdrawio-diagrams%2Fdiagrams%2Fmath.xml)

still not working in export pdf

**Comment by wookayin** [comment]
@alderg Seems that we can just adjust the bounding box to make the clipped region visible again.

**Comment by davidjgraph** [comment]
@wookayin Please submit your fix as a PR and we'll review it.

**Comment by holyseven** [comment]
Hello everyone. So, how can we change the font on the math typesetting to "Latin-Modern" in draw.io?

**Comment by SiBensberg** [comment]
I strongly agree with this feature request. Some professors are very strict with the fonts. I love drawio because it is intuitive and fast. But I need this font. :/

**Comment by davidjgraph** [comment]
Please don't +1, it generates noise in the comment. Just thumbs up the original request.

**Comment by fredguth** [comment]
> "HTML-CSS": { availableFonts: ["TeX"] }

Where do I change the config?

**Comment by alderg** [comment]
This will be added in the next release as the clipping problem mentioned above was fixed in 12.5.0. However, the font metrics are different so some shapes my have to be resized or text overflow may have to be changed to visible.
<img width="228" alt="text-overflow" src="https://user-images.githubusercontent.com/921200/79727418-aa57e080-82ec-11ea-9277-1b80b4ae33a6.png">

**Comment by zivy90** [comment]
> > "HTML-CSS": { availableFonts: ["TeX"] }
> 
> Where do I change the config?

Hi, @fredguth and @wookayin， I also wonder where should I modify the configure file. Thank you!

**Comment by alderg** [comment]
https://github.com/jgraph/drawio/blob/master/src/main/webapp/js/diagramly/Editor.js#L1379
https://github.com/jgraph/drawio/blob/master/src/main/webapp/js/diagramly/Editor.js#L5968

**Comment by zivy90** [comment]
@alderg Thanks for the reply. I saw the changes are focused on SVG, is there any solutions for PDF?

**Comment by alderg** [comment]
PDF export uses the same configuration.

**Comment by zivy90** [comment]
I have tested, but it has another problem. Below is the PDF output. It seems math font is bold automatically. 
![image](https://user-images.githubusercontent.com/13672525/79951086-a5d92680-84aa-11ea-8cdb-43cb2e1fe861.png)

**Comment by alderg** [comment]
The TeX font looks like this. I think this PDF viewer makes it look worse than it is on this zoom level, if you zoom in it should match what you see on the screen.

**Comment by zivy90** [comment]
Yes, you are right. Thanks again.

**Comment by v-iashin** [comment]
> The TeX font looks like this. I think this PDF viewer makes it look worse than it is on this zoom level, if you zoom in it should match what you see on the screen.

I am afraid it is not the reader. 
Zoomed out: https://imgur.com/Xflyh34
Zoomed in: https://imgur.com/t7RAJ9i

**Comment by idansc** [comment]
> The TeX font looks like this. I think this PDF viewer makes it look worse than it is on this zoom level, if you zoom in it should match what you see on the screen.

Is there anything new that causing the bold-looking? 
When I zoom it looks ok, but I and probably others don't read documents with zoomed in

**Comment by EloiZ** [comment]
Hi,
in addition to being bold, the rendered math symbols cannot be selected anymore in the pdf. Do you know how to revert this behavior please?

**Comment by alderg** [comment]
We've added a new URL parameter math-output=html in 13.1.13 so that PDFs can be created via File, Print and Print to PDF in the browser with the previous math rendering. See https://desk.draw.io/support/solutions/articles/16000032875 for details.

**Comment by alderg** [comment]
Fixed bold math in PDF export. For text selection, use [https://app.diagrams.net/?math-output=html](https://app.diagrams.net/?math-output=html) with client-side PDF export via File, Print and Print to PDF.

**Comment by EloiZ** [comment]
Thanks, it is not longer bold anymore with the trick.
However, the produced math symbols still cannot be highlighted (selected with a mouse) in a pdf reader

**Comment by bernardo-silva** [comment]
> Fixed bold math in PDF export. For text selection, use https://app.diagrams.net/?math-output=html with client-side PDF export via File, Print and Print to PDF.

Is there an easy way to crop the pdf to the diagram size with this method?
