### ISSUE TITLE
Background color not exported to PDF

### ISSUE THREAD

**Issue by flaimo** [jgraph/drawio#528]
When exporting a diagram, which has a page with a background color set, the color is not exported to the pdf.

[Untitled Diagram(2).pdf](https://github.com/jgraph/drawio/files/3503558/Untitled.Diagram.2.pdf)

[green_background.drawio.zip](https://github.com/jgraph/drawio/files/3503560/green_background.drawio.zip)

**Comment by davidjgraph** [comment]
What are the steps and environment to recreate?

**Comment by flaimo** [comment]
Environment: https://www.draw.io/
Steps:

1. Create new blank diagram
2. Create second page
3. Define different color for the diagram background for that page
![Screenshot 2019-08-17 at 02 02 15](https://user-images.githubusercontent.com/416323/63203945-1d8cc100-c093-11e9-81c6-128970fe5dbb.png)
4. Switch back to first page
5. Export as PDF (all pages) → NOK: All page are white

It seems as the pdf export takes the background color that is defined for the currently displayed/active page and applies it to all pdf pages.

**Comment by alderg** [comment]
Fixed in 11.1.5.

**Comment by jlnobles** [comment]
The problem still exists if Grid is enabled during pdf-export.
![Capture](https://user-images.githubusercontent.com/81612154/222976263-6014f4f7-3e46-46f6-b1f6-17b444f2acd5.PNG)

**Comment by davidjgraph** [comment]
@jlnobles please create a new ticket if there are a set of conditions that recreate the problem but vary from the original report.
