### ISSUE TITLE
Copy/Paste of figures doesn't work any more on diagrams.net website

### ISSUE THREAD

**Issue by cdancette** [jgraph/drawio#843]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**To Reproduce**

Create a diagram
Select it
Ctrl + c
Ctrl + v 

Instead of pasting the figure, it pastes its text representation. 

**Expected behavior**

The figure is copied

**Screenshots**
![image](https://user-images.githubusercontent.com/10550327/78762941-d71f0600-7984-11ea-9a91-7831ba751676.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
Last online version (12.9.8)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 74

**Additional context**

I noticed this yesterday

**Comment by davidjgraph** [comment]
Repeated FF 74.0 MacOS 10.15.3

**Comment by cdancette** [comment]
Additional information: it works as expected when I right click -> Paste here. It's only Ctrl+v that doesn't work.

**Comment by alderg** [comment]
Fixed in 12.9.10.

**Comment by cdancette** [comment]
Thanks for the amazing work !

**Comment by bravoecho** [comment]
Currently this is still an issue for me, Chrome on Ubuntu 20.04

**Comment by davidjgraph** [comment]
@bravoecho please open a new issue with environment details.

**Comment by SandyChapman** [comment]
I'm seeing this today in 13.1.3
Mac OS 10.15.3
Chrome 83.0.4103.61 (Official Build) (64-bit)

Right-click copy and right-click paste works.
Menu options work.
Neither Cmd+C nor Cmd+V works.

**Comment by elocke-abroaden** [comment]
Seeing this issue for the past week.  

Google Chrome | 83.0.4103.61 (Official Build) (64-bit)
OS | Linux

Can only copy/paste using menus. Ctrl+C and Ctrl+V does not work.

**Comment by alderg** [comment]
Are you using a file created with the C4 plugin? What version number do you see in the last entry of the Help menu? What Linux version are you using?

**Comment by elocke-abroaden** [comment]
> Are you using a file created with the C4 plugin? What version number do you see in the last entry of the Help menu? What Linux version are you using?

Hi Alderg, apologies for the delayed reply. 

To my knowledge, I am not using the C4 plugin (I believe you're referring to this? https://tobiashochguertel.github.io/c4-draw.io/) 

I have version 13.1.11 in the help menu. 

I'm using Pop OS 20.04 (based on Ubuntu 20.04) 64-bit.

**Comment by SandyChapman** [comment]
@alderg Although I have used the C4 plugin in the past, the diagrams I'm seeing this issue on are not using this plugin. 13.1.15 for diagrams.net version in the help menu. Cmd+D for duplicate does work, so at least there's a convenient workaround.

**Comment by alderg** [comment]
@SandyChapman The problem is that we're unable to reproduce the problem. What are the minimal steps to reproduce the problem?

**Comment by SandyChapman** [comment]
@alderg Minimum steps are to open a new diagram, add a box and try to copy and paste using cmd+c, cmd+v. I've recorded a short video. You can see when I press cmd+c, cmd+v on the keyboard, the Mac OS menu bar's "edit" menu flickers showing the OS has handle the cmd+c and cmd+v hotkeys.

https://drive.google.com/file/d/1ocEhC2R7P70usdBmHKLcxYkwRkOJBKhA/view?usp=sharing

**Comment by alderg** [comment]
@SandyChapman Are there any errors in the console and is this also broken in Incognito mode?

**Comment by SandyChapman** [comment]
Does not work in Incognito Mode either. No errors printed in the dev console. @alderg

**Comment by cdancette** [comment]
Hi @alderg @davidjgraph I'm seeing this issue again as well, on the web version (on Firefox 76).

Should I create a new issue ?

**Comment by davidjgraph** [comment]
This issue is fine, but we just need the exact environment and exact reproduction steps please.

**Comment by cdancette** [comment]
The reproduction steps are exactly the same as in the original issue.

Exact environment:

Draw.io web version, 13.1.11

Os: Linux Solus
Browser: Firefox 76

**Comment by davidjgraph** [comment]
All extensions off in FF when tested?

**Comment by jonathanTIE** [comment]
Hello,
I have the same issue on the web version 13.1.11, Browser : Firefox 76, OS : Windows 10.
Ctrl+c and click paste here works but not ctrl + v. Ctrl+D has no issues.

**Comment by alderg** [comment]
Fixed in 13.1.12 for Firefox. (Not sure if it fixes the problem in Chrome as we were unable to reproduce that.)

**Comment by cdancette** [comment]
@davidjgraph I tried in another firefox profile, and the ctrl + c, ctrl+v worked.
I am trying to disable extentions to see which one might cause the issue.

**Comment by davidjgraph** [comment]
Sure you didn't load .12 for that test, it went out 14 minutes ago.

**Comment by SandyChapman** [comment]
I can confirm that 13.1.12 still isn't working for me on Chrome (MacOS).

**Comment by cdancette** [comment]
@davidjgraph You're right. It is fixed for me in 13.1.12 with all extensions enabled.

**Comment by Tiduster** [comment]
I confirm, fix in 13.1.12 in Firefox for me as well.
Thanks a lot!

**Comment by davidjgraph** [comment]
@SandyChapman could you open a new issue for this in Chrome please? I don't want to overload the same ticket to avoid an overly long thread that covers multiple bugs.

**Comment by cdancette** [comment]
Thanks a lot for fixing it so quickly !

**Comment by SandyChapman** [comment]
@davidjgraph Opened #949

**Comment by chanansh** [comment]
when I copy-paste an image to drawio it appears as a transparent empty image even if I upload it from disk. Tried several different images.
